name: trs-extraction 
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
  - xformers
dependencies:
  - python=3.11.12
  - pip=25.0.1
  - pytorch-cuda=12.4
  - pip:
      - -r requirements_dev.txt
      - -r requirements.txt